### ISSUE TITLE
suggestion to add lighting metadata to Datapoint

### ISSUE THREAD

**Issue by AsaphLightricks** [DatagenTech/dgutils#3]
to:
https://github.com/DatagenTech/dgutils/blob/59b518946d29e5be16b2b4808e334f41144fa55f/DataLoader/DatapointHandler.py#L98-L102
add the following:
```
        if "environment" in fn:
            for env_dict in local_dict["environments"]:
                if env_dict['image_name'] == os.path.basename(self._render_path):
                    local_dict = env_dict
                    break
```
to:
https://github.com/DatagenTech/dgutils/blob/59b518946d29e5be16b2b4808e334f41144fa55f/DataLoader/DatapointHandler.py#L197-L201
add:
```
            "environment.json " 
```
to:
https://github.com/DatagenTech/dgutils/blob/59b518946d29e5be16b2b4808e334f41144fa55f/DataLoader/Datapoint.py#L55-L58
add:
```
            # Image modalities handlers. This is a private field. 
            # Use the property fields below to access image modalities 
            image_handlers: Structure 
  
             # lighting
              image_name: str
              environment: str
              time_of_day: str
              background: str
```

**Comment by rlemberskyDatagen** [comment]
Thank you, we will pass the feature request to Product.
