### ISSUE TITLE
Error in datagen.load

### ISSUE THREAD

**Issue by vkress** [DatagenTech/dgutils#5]
I am trying to run the notebook 011_hic_body_pose.ipynb. However, during datagen.load I get a FileNotFoundError, because it is looking for data at the path '..\\resources\\hic_in_cabin\\scene_00001\\frames\\001\\frames\\environment.json'. In case of incabin scenarios the data are organized in folders named by the camera perspective. For example, in the above example the correct path would be '..\\resources\\hic_in_cabin\\scene_00001\\frames\\001\\media_dashboard_camera\\environment.json'. Is there a way to influence datagen.load?

**Comment by rlemberskyDatagen** [comment]
Thanks for bringing this up, vkress. Was able to reproduce. Putting in a fix request. Will update with eta.

**Comment by rlemberskyDatagen** [comment]
Fixed in latest SDK release
