### ISSUE TITLE
Issue with camera and CameraJsonParser script

### ISSUE THREAD

**Issue by sidsingla** [DatagenTech/dgutils#6]
Hi,
I think there is an issue with the script https://github.com/DatagenTech/dgutils/blob/7715b399340abdec07970a5e64fe834f5e5b7b2f/Notebooks/scripts/json_parser.py#L33 as Camera Metadata doesn't have ["orientation"]["rotation"] but look_at_vector and up_vector.
Maybe the script needs updation?

Thanks!

**Comment by rlemberskyDatagen** [comment]
On it, @sidsingla. Will update you shortly on the status.

*Russell Lembersky*
*Mgr. Computer Vision Product Specialists*

**Comment by rlemberskyDatagen** [comment]
@sidsingla. The json_parser file is not a generic parser for our dataset, sorry for the confusion. To parse our data, please use our sdk, you can find info and download instructions on the readme here: 

https://github.com/DatagenTech/dgutils/tree/master/Notebooks#readme

Then follow the instructions in notebook #2 to load our data:
https://github.com/DatagenTech/dgutils/blob/master/Notebooks/002_dataset%20_overview.ipynb


If you're instead interested in visualizing a preview of the framing of the head pre-render and offline:
 
The in_frame notebook returns a visual approximation of the synthetic head as it would be in the generated frame. The input to this notebook is not the camera_metadata.json file, but rather a locally defined dictionary in the notebook: 

camera_request = {
         "name": "camera_1",
         "type": "perspective",
         "wavelength_kind": "rgb",
         "location": {
            "x": 0.0,
            "y": -1.6,
            "z": 0.12
         },
         "orientation": {
            "rotation": {
               "yaw": 20.0,
               "pitch": -10.0,
               "roll": 40.0
            },
         },

**Comment by sidsingla** [comment]
Oh ok! I think it will be better to have it as a Generic Parser for your repo, else maybe move this script to a local directory or have a comment aleast to which Notebook it pertains. All the scripts in the **_scripts_** dir should be generic.

Thankyou!
Closing the issue!
